name: Build and Deploy Kafka Monitor Application

on:
  push:
    branches:
      - master  # 适配你的主分支名

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build with Maven
        run: |
          cd kafka-monitor-application
          mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          cd kafka-monitor-application
          docker build -t registry.cn-hangzhou.aliyuncs.com/jast-zsh/kafka-monitor:1.1 -f Dockerfile .

      - name: Login to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

      - name: Push Docker image to Aliyun
        run: docker push registry.cn-hangzhou.aliyuncs.com/jast-zsh/kafka-monitor:1.1

      - name: Cleanup
        run: docker rmi registry.cn-hangzhou.aliyuncs.com/jast-zsh/kafka-monitor:1.1
