name: 发布Kafka消费者组监控程序到阿里云Docker镜像仓库

on:
  push:
    branches:
      - master  # 当Master分支提交代码时触发

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 设置JDK1.8环境
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: 项目打包
        run: |
          cd kafka-monitor-application
          mvn clean package -DskipTests

      - name: 生成Docker镜像
        run: |
          docker system prune -f
          cd kafka-monitor-application
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker build -t registry.cn-hangzhou.aliyuncs.com/jast-tools/kafka-monitor:${VERSION} --build-arg VERSION=${VERSION} -f Dockerfile .

      - name: 登录阿里云
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

      - name: 提交镜像到阿里云容器仓库
        run: |
          cd kafka-monitor-application
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker push registry.cn-hangzhou.aliyuncs.com/jast-tools/kafka-monitor:${VERSION}
          docker push registry.cn-hangzhou.aliyuncs.com/jast-tools/kafka-monitor:latest
