name: Build and Deploy Kafka Monitor Application

on:
  push:
    branches:
      - master  # 适配你的主分支名

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build with Maven
        run: |
          cd kafka-monitor-application
          mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker system prune -f
          cd kafka-monitor-application
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker build -t registry.cn-hangzhou.aliyuncs.com/jast-tools/kafka-monitor:${VERSION} --build-arg VERSION=${VERSION} -f Dockerfile .

      - name: Login to Aliyun Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

      - name: Push Docker image to Aliyun
        run: |
          cd kafka-monitor-application
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker push registry.cn-hangzhou.aliyuncs.com/jast-tools/kafka-monitor:${VERSION}
